@blogsUrl = http://localhost:3001/api/blogs

### Get all blog entries
GET {{blogsUrl}}

### Add a new blog entry
POST {{blogsUrl}}
Content-Type: application/json

{
	"title": "NodeJS: first steps",
	"author": "Alisher Aliev",
	"url": "https://alishstrong.com/blog/nodejs-first-steps",
	"likes": 5
}

### Add a new blog entry, authenticated
POST {{blogsUrl}}
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaXNoX3N0cm9uZyIsImlkIjoiNjBkNmE2N2E2NmQ3YzIyMDQ0NzhjNjllIiwiaWF0IjoxNjI0NzAxNjI5fQ.XTyjDoh9XaMgcbMwRA6OWLDnVMIb9EXE50MEX6HXOWA

{
	"title": "NodeJS: first steps",
	"author": "Alisher Aliev",
	"url": "https://alishstrong.com/blog/nodejs-first-steps",
	"likes": 5
}